ALTER DATABASE ElevateDev SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE ElevateDev

ALTER DATABASE PMCPBranchDev SET OFFLINE

ALTER DATABASE aw2014 SET ONLINE
ALTER DATABASE aw2014 SET MULTI_USER
