DECLARE @TimeZone VARCHAR(50)
EXEC MASTER.dbo.xp_regread 'HKEY_LOCAL_MACHINE',
'SYSTEM\CurrentControlSet\Control\TimeZoneInformation',
'TimeZoneKeyName',@TimeZone OUT
SELECT @TimeZone
GO

SELECT SYSDATETIME() AS SYSDATETIME  
	,GETDATE() AS GETDATE  
    ,SYSUTCDATETIME() AS SYSUTCDATETIME  
    --,CURRENT_TIMESTAMP AS TIMESTAMP
    ,GETUTCDATE() AS GETUTCDATE
	,SYSDATETIMEOFFSET() AS SYSDATETIMEOFFSET  

SELECT SYSDATETIMEOFFSET()
	,CONVERT(DATE, SYSDATETIMEOFFSET())
	,CONVERT(TIME, SYSDATETIMEOFFSET())
	,DATEPART(tz, SYSDATETIMEOFFSET())
